/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/



		-- find the revenue generated by each store

		SELECT 
		store_id,
		SUM(total_sales) AS total_revenue
		FROM diamond.ProductSales
		GROUP BY store_id
		ORDER BY SUM(total_sales) DESC;

		  -- find the cost generated by the each store
		SELECT 
		store_id,
		SUM(total_cost) AS total_revenue
		FROM diamond.ProductSales
		GROUP BY store_id
		ORDER BY SUM (total_cost) DESC;

		-- find the profits generated by each store
		SELECT 
		store_id,
		(SUM(total_sales) - SUM(total_cost))AS total_profits
		FROM diamond.ProductSales
		GROUP BY store_id
		ORDER BY (SUM(total_sales) - SUM(total_cost)) DESC;



		-- find the product category that generate most revenue
		SELECT 
		product_category,
		SUM(total_sales) AS total_revenue
		FROM diamond.ProductSales
		GROUP BY product_category
		ORDER BY SUM(total_sales) DESC;


		-- find the product category with the most cost
		SELECT 
		product_category,
		SUM(total_cost) AS total_cost
		FROM diamond.ProductSales
		GROUP BY product_category
		ORDER BY SUM(total_cost) DESC;


		 -- profits by category
		SELECT
		product_category,
		(SUM(total_sales) - SUM(total_cost))AS total_profits
		FROM diamond.ProductSales
		GROUP BY product_category
		ORDER BY (SUM(total_sales) - SUM(total_cost)) DESC;

		-- product generates the most revenue
		SELECT 
		product_name,
		(SUM(total_sales) - SUM(total_cost))AS total_profits
		FROM diamond.ProductSales
		GROUP BY product_name
		ORDER BY (SUM(total_sales) - SUM(total_cost)) DESC;


		-- which product category is being bought the most

		SELECT 
		product_category,
		SUM(units) AS total_units
		FROM diamond.ProductSales
		GROUP BY product_category
		ORDER BY SUM(units) DESC;


		-- which product  is being bought the most
		SELECT 
		product_name,
		SUM(units) AS total_units
		FROM diamond.ProductSales
		GROUP BY product_name
		ORDER BY SUM(units) DESC;


		 -- find store with the most stocks  
		 SELECT 
		store_name,store_city, store_location,
		SUM(stock_on_hand) AS total_stock
		FROM diamond.StoreInventory
		GROUP BY store_name, store_city, store_location
		ORDER BY SUM(stock_on_hand) DESC;
